# Generated by Django 3.2.9 on 2021-11-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.TextField()),
                ('ner', models.TextField()),
                ('query', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'chatbot_train_data',
            },
        ),
    ]
